### ISSUE TITLE
File garbled

### ISSUE THREAD

**Issue by larsbrinkhoff** [RickCarlino/fbbs2#2]
The file modern/FBBS2.DOC is garbled.  The pristine copy is too, but it should of course be left alone.

I tested clearing the high bit, that makes the file readable.  Are more files affected?

**Comment by RickCarlino** [comment]
Great work @larsbrinkhoff I see some garbled text in the *.SCR files, but I am unsure if that is due to file corruption.

Could you send a PR for the *.DOC file fix? Very excited to see the changes.

**Comment by larsbrinkhoff** [comment]
I also saw some possible garbled text in a .DAT file.  But let's close this for now until we know more.
